### ISSUE TITLE
你好，我用pycharm，当变量超长的时候，有什么办法让他自动换行么？

### ISSUE THREAD

**Issue by AaronConlon** [firejq/zhihu_scrapy#1]
你好，我用pycharm，当变量超长的时候，有什么办法让他自动换行么？像你代码那样。

**Comment by AaronConlon** [comment]
![image](https://user-images.githubusercontent.com/23721611/30541292-55872e62-9cad-11e7-9e21-40dee3ae0ae7.png)
Use soft wraps in editor

**Comment by firejq** [comment]
可以试试这款插件 [AutoPEP8](https://segmentfault.com/a/1190000005816556)    
设置快捷键后挺方便的
